Source: https://numpy.org/doc/stable/user/absolute_beginners.html

## Importing Library

In [2]:
import numpy as np

## Numpy Arrays

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

![np_array](../images/np_array.png)

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]) # 3 rows 4 columns 
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
a.shape

(3, 4)

ndarray = N-dimensional array

What is tensor? => https://www.youtube.com/watch?v=f5liqUk0ZTw

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(2)

array([1., 1.])

Important and frequently used parameter = dtype

In [8]:
# https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.int32
np.ScalarType

(int,
 float,
 complex,
 int,
 bool,
 bytes,
 str,
 memoryview,
 numpy.bool_,
 numpy.complex64,
 numpy.clongdouble,
 numpy.complex128,
 numpy.float16,
 numpy.float32,
 numpy.longdouble,
 numpy.float64,
 numpy.int8,
 numpy.int16,
 numpy.int32,
 numpy.intc,
 numpy.int64,
 numpy.timedelta64,
 numpy.datetime64,
 numpy.object_,
 numpy.bytes_,
 numpy.str_,
 numpy.uint8,
 numpy.uint16,
 numpy.uintc,
 numpy.uint32,
 numpy.uint64,
 numpy.void)

In [9]:
np.ones(5, dtype = np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [10]:
# Faster than zeros()
# Initial content is random
# Depends on the state of the memory
np.empty(3)

array([6.23040373e-307, 1.60219035e-306, 9.34597567e-307])

In [11]:
np.arange(4)

array([0, 1, 2, 3])

np.arange(first_number, last_number, step_size)

In [12]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

## Adding, removing, and sorting elements

In [13]:
# Sorting (Siralama)
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [14]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
# Concatenate (Birlestime)
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [16]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [18]:
print("X:", x, "\n\nShape:", x.shape)

X: [[1 2]
 [3 4]] 

Shape: (2, 2)


In [19]:
print("Y:", y, "\n\nShape:", y.shape)

Y: [[5 6]] 

Shape: (1, 2)


In [20]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
np.concatenate((x, y), axis = None)

array([1, 2, 3, 4, 5, 6])

In [22]:
np.concatenate?

Docstring:
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may occur. Defaults to 'same_kind'.

    .. versionadded:: 1.20.0

Returns

## Shape and size of an array

In [23]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

ndarray.ndim =  eksen, boyut sayisi

In [24]:
array_example.ndim

3

ndarray.shape = dizinin her boyutu boyunca yer alan ogelerin sayisini gosteren bir tamsayi kumesi

Ex:
2 satir ve 3 kolon -> shape = (2, 3)

In [25]:
# 1. dim - 3 tane 2d array
# 2. dim - 2 tane 1d array
# 3. dim - 4 tane sayi
array_example.shape

(3, 2, 4)

ndarray.size = toplam eleman sayisi<font size="2">*</font>

<font size="2"> *_Shape degerlerinin carpimidir._</font>

In [26]:
array_example.size

24

## Reshaping an array

In [27]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [28]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

Uyari: Eski array'in `size`'i `=` Yeni array'in `shape`'inin degerleri carpimi

In [29]:
a.size == (b.shape[0]*b.shape[1])

True

## Indexing and slicing

In [30]:
data = np.array([1, 2, 3])

In [31]:
data[1]

2

In [32]:
data[0:2]

array([1, 2])

In [33]:
data[1:]

array([2, 3])

In [34]:
data[-2:]

array([2, 3])

![np_indexing](../images/np_indexing.png)

In [35]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
a[a < 5]

array([1, 2, 3, 4])

In [37]:
five_up = (a >= 5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
divisible_by_2 = a[a % 2 == 0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [39]:
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
# Aslinda bir filtre olustumus olduk
(a > 2) & (a < 11)

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [41]:
five_up_filter = (a > 5) | (a == 5)
five_up_filter

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [42]:
# 1. array -> 1. dim indeksleri
# 2. array -> 2. dim indeksleri
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [43]:
# Filtreleme yapabiliriz ve istenen kosulu
# saglayan degerlerin indeks array'i elde edebiliriz.
a[b]

array([1, 2, 3, 4])

In [44]:
# Aranan oge dizide yoksa, dondurulen array indeksi bos olacaktir.
not_there = np.nonzero(a == 42)
not_there

(array([], dtype=int64), array([], dtype=int64))

In [45]:
list_of_coordinates= list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


## Basic array operations
addition, subtraction, multiplication, division, and more

In [46]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

![np_data_plus_ones](../images/np_data_plus_ones.png)

In [47]:
data + ones

array([2, 3])

![np_sub_mult_divide](../images/np_sub_mult_divide.png)

In [48]:
data - ones

array([0, 1])

In [49]:
data * data

array([1, 4])

In [50]:
data / data

array([1., 1.])

In [52]:
data.sum()

3

In [56]:
b = np.array([[1, 1], [2, 2], [4, 3]])
b

array([[1, 1],
       [2, 2],
       [4, 3]])

In [55]:
# Her bir satirin toplami
b.sum(axis=0)

array([7, 6])

In [57]:
# Her bir sutunun toplami
b.sum(axis=1)

array([2, 4, 7])

## Broadcasting

Burada, bir array ile tek bir sayi arasında (vektor ile skaler arasındaki islem olarak da adlandirilabilir) veya iki farkli boyuttaki array'ler arasinda islem gerceklestirmek istenebilir. Mesela, array'de (buna "veri" diyecegiz) mil cinsinden mesafe hakkinda bilgiler icerebilir, ancak bilgileri kilometreye donusturmek isteyebiliriz. Bu islemi su sekilde yapabiliriz:

![np_multiply_broadcasting](../images/np_multiply_broadcasting.png)

In [58]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

NumPy, carpma isleminin her hucrede gerceklesmesi gerektigini anlar. Bu kavrama `broadcast` denir.

## Daha Faydali Array Fonksiyonlari
#### Aggregation Functions: 
* maximum
* minimum
* sum
* mean
* product
* standard deviation
* ...

In [64]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

![np_aggregation](../images/np_aggregation.png)

In [69]:
print("Max: ", a.max())
print("Min: ", a.min())
print("Sum: ", a.sum())
print("Min of each column", a.min(axis=0))
print("Mean: ", a.mean())
print("Prod: ", a.prod())
print("Std: ", a.std())


Max:  0.82485143
Min:  0.05093587
Sum:  4.8595784
Min of each column [0.12697628 0.05093587 0.26590556 0.5510652 ]
Mean:  0.4049648666666667
Prod:  1.4517216120884712e-06
Std:  0.21392120766089617


## Creating matrices

You can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.

![Alt text](../images/np_create_matrix.png)

In [70]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

![np_matrix_indexing](../images/np_matrix_indexing.png)

In [72]:
print(data[0, 1], "\n")
print(data[1:3], "\n")
print(data[0:2, 0])

2 

[[3 4]
 [5 6]] 

[1 3]


![np_matrix_aggregation](../images/np_matrix_aggregation.png)

In [ ]:
print("Max: ", data.max())
print("Min: ", data.min())
print("Sum: ", data.sum())

In [73]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

![np_matrix_aggregation_row](../images/np_matrix_aggregation_row.png)

In [74]:
print("Max of each column: ", data.max(axis=0))
print("Max of each row: ", data.max(axis=1))

Max of each column:  [5 6]
Max of each row:  [2 5 6]


![np_matrix_arithmetic](../images/np_matrix_arithmetic.png)

In [75]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

![np_matrix_broadcasting](../images/np_matrix_broadcasting.png)

In [76]:
# broadcast kurali gecerli!
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [78]:
# NumPy, N boyutlu array'leri loop'ta yazdirirken son eksen en hizli, birinci eksen ise en yavas yazidirilir
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

## Generating random numbers

In [83]:
# Generator class'indaki integers fonksiyonu kullanilir.
# endpoint=True yapilirsa en buyuk sayi da isleme katilir.
# 0 ile 4 arasında rasgele sayilardan olusan 2 x 4'luk matris
rng.integers(5, size=(2, 4)) 

array([[1, 1, 2, 4],
       [4, 0, 0, 3]], dtype=int64)

In [82]:
# Daha basit yontem
rng = np.random.default_rng()
rng.random(3)

array([0.02128085, 0.92075707, 0.38731159])

## Unique items and counts

In [85]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [93]:
unique_values = np.unique(a)
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [94]:
unique_values, indices_list = np.unique(a, return_index=True)
print("Unique Values          : ", unique_values)
print("Unique Values' Indices : ", indices_list)

Unique Values          :  [11 12 13 14 15 16 17 18 19 20]
Unique Values' Indexes :  [ 0  2  3  4  5  6  7 12 13 14]


In [95]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print("Unique Values    : ", unique_values)
print("Occurrence Count : ", occurrence_count)

Unique Values    :  [11 12 13 14 15 16 17 18 19 20]
Occurrence Count :  [3 2 2 2 1 1 1 1 1 1]


In [97]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)

In [110]:
print("Unique Values          : ", unique_values)
print("Unique Rows            : ", unique_rows)
print("Unique Values' Indices : ", indices_list)
print("Occurrence Count       : ", occurrence_count)

Unique Values          :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
Unique Rows            :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Unique Values' Indices :  [ 0  2  3  4  5  6  7 12 13 14]
Occurrence Count       :  [2 1 1]


## Transposing and reshaping a matrix

![np_reshape](../images/np_reshape.png)

In [114]:
data = np.arange(6)
data

array([0, 1, 2, 3, 4, 5])

In [116]:
data = data.reshape(2, 3)
data

array([[0, 1, 2],
       [3, 4, 5]])

In [117]:
data = data.reshape(3, 2)
data

array([[0, 1],
       [2, 3],
       [4, 5]])

![np_transposing_reshaping](../images/np_transposing_reshaping.png)

In [111]:
arr = np.arange(6).reshape((2, 3))
print("Normal Matrix:\n", arr, "\n")
print("Transposed Matrix:\n", arr.T)

Normal Matrix:
 [[0 1 2]
 [3 4 5]] 

Transposed Matrix:
 [[0 3]
 [1 4]
 [2 5]]


In [112]:
# ya da
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

## Access the docstring for more information

Dokumantasyon basvurulabilecek en iyi yer olabilir, kod yazarken de faydalanmak mumkun. Sadece spesifik kutuphanelerin degil, kendi kodlarinizdaki fonksiyonlari hatirlamak icin de kullanabilirsiniz.

In [118]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [119]:
max?

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method


In [123]:
data?

Type:        ndarray
String form:
[[0 1]
 [2 3]
 [4 5]]
Length:      3
File:        c:\users\beste\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any

You can obtain information about the function

In [128]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method


You can reach another level of information by reading the source code of the object you’re interested in. Using a double question mark (??) allows you to access the source code.

In [126]:
def sqrt(a):
  '''Return a ** 2'''
  return a ** 2

In [ ]:
sqrt??